config/routes.rb
Ftweb::Application.routes.draw do
  root :to => "welcome#index"
  match "locale/:id" => "welcome#set_language", :as => "set_language"

  namespace :manager do
    match "index" => "welcome#index"
    resources :languages
    resources :companies
    resources :categories do 
      member do
        get 'insert'
      end
      collection do
        post 'bat_del'  # 批量删除
      end
    end
    resources :contents do 
      member do
        get 'insert'
      end
      collection do
        post 'bat_del'  # 批量删除
      end
    end
  end

end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :code, :default, :link, :memo
  validates :code, :uniqueness => true
  validates :code, :presence => true

  has_many :companies
  has_many :categories
  has_many :contents
end

app/controllers/manager/categories_controller.rb
# *-*  coding: utf-8  *-*
class Manager::CategoriesController < ApplicationController
  layout "manager"

  def index
    @categories = Category.order("sort")
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def insert
    parent_category = Category.find(params[:id])
    @category = Category.new
    @category.parent_id = params[:id]
    @category.company_id = parent_category.company_id

    render :action => "new"
  end

  def create
    @category = Category.new(params[:category])

    if @category.save
      redirect_to manager_categories_path, :notice => "成功新增内容:#{@category.title}"
    else
      render :action => "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(params[:category])
      redirect_to manager_categories_path, :notice => "内容:#{@category.title}更新完成。"
    else
      render :action => "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to manager_categories_path
  end

  # 批量删除
  def bat_del
    @categories = Category.find(params[:category_ids])
    @categories.each do |category|
      category.destroy
    end

    redirect_to manager_categories_path
  end
end

app/controllers/manager/companies_controller.rb
# *-* coding:utf-8 *-*
class Manager::CompaniesController < ApplicationController
  layout "manager"
  def index
    @companies = Company.all
  end

  def show
    @com = Company.all
  end

  def new
    @com = Company.new
  end

  def create
    @com = Company.new(params[:company])

    if @com.save
      redirect_to manager_companies_path, :notice => "新增公司:#{@com.name}"
    else
      render :action=> "new"
    end
  end

  def edit
    @com = Company.find(params[:id])
  end

  def update
    @com = Company.find(params[:id])

    if @com.update_attributes(params[:company])
      redirect_to manager_companies_path, :notice => "#{@com.name} 相关信息更新完成!"
    else
      render :action => "edit"
    end
  end

  def destroy
    @com = Company.find(params[:id])
    @com.destroy

    redirect_to manager_companies_path
  end
end

app/controllers/manager/contents_controller.rb
# *-* coding:utf-8 *-*
class Manager::ContentsController < ApplicationController
  layout "manager"

  def index
    @contents = Content.order("sort")
  end

  def show
    @content = Content.find(params[:id])
  end

  def new
    @content = Content.new
  end

  def insert
    parent_content = Content.find(params[:id])
    @content = Content.new
    @content.parent_id = params[:id]
    @content.company_id = parent_content.company_id

    render :action => "new"
  end

  def create
    @content = Content.new(params[:content])

    if @content.save
      redirect_to manager_contents_path, :notice => "成功新增内容:#{@content.title}"
    else
      render :action => "new"
    end
  end

  def edit
    @content = Content.find(params[:id])
  end

  def update
    @content = Content.find(params[:id])

    if @content.update_attributes(params[:content])
      redirect_to manager_contents_path, :notice => "内容:#{@content.title}更新完成。"
    else
      render :action => "edit"
    end
  end

  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    redirect_to manager_contents_path
  end

  def bat_del
    @contents = Content.find(params[:content_ids])
    @contents.each do |content|
      content.destroy
    end

    redirect_to manager_contents_path
  end
end

app/controllers/manager/languages_controller.rb
# *-* coding:utf-8 *-*
class Manager::LanguagesController < ApplicationController
  layout "manager"
  def index
    @languages = Language.all
  end

  def show
    @lan = Language.find(params[:id])
  end

  def new
    @lan = Language.new
  end

  def create
    @lan = Language.new(params[:language])

    if @lan.save
      redirect_to manager_languages_path, :notice =>"新语言#{@lan.memo}已经成功增加！"
    else
      render :action=>"new"
    end
  end

  def edit
    @lan = Language.find(params[:id])
  end

  def update
    @lan = Language.find(params[:id])

    if @lan.update_attributes(params[:language])
      redirect_to manager_languages_path, :notice =>"#{@lan.memo}已经更新！"
    else
      render :action=>"edit"
    end
  end

  def destroy
    @lan = Language.find(params[:id])
    @lan.destroy

    redirect_to manager_languages_path
  end
end

app/controllers/manager/welcome_controller.rb
class Manager::WelcomeController < ApplicationController

  layout  "manager"
  def index

  end
end

app/helpers/manager/categories_helper.rb
module Manager::CategoriesHelper
end

app/helpers/manager/companies_helper.rb
module Manager::CompaniesHelper
end

app/helpers/manager/contents_helper.rb
module Manager::ContentsHelper
end

app/helpers/manager/languages_helper.rb
module Manager::LanguagesHelper
end

app/helpers/manager/welcome_helper.rb
module Manager::WelcomeHelper
end

app/views/manager/languages/_form.html.haml
= form_for [:manager, @lan] do |f|

  .control-group{:class=>"#{'error' unless @lan.errors[:code].empty?}"}
    =f.label :code
    .controls
      =f.text_field :code
      %span
        - if @lan.errors[:code].empty?
          可以参看<a href="https://github.com/svenfuchs/rails-i18n">这里</a>
        - else
          =@lan.errors[:code]

  .control-group{:class=>"#{'error' unless @lan.errors[:link].empty?}"}
    =f.label :link
    .controls
      =f.text_field :link
      %span
        - if @lan.errors[:link].empty?
          须以http://开头， 后面的/不能少
        - else
          =@lan.errors[:link]

  .control-group{:class=>"#{'error' unless @lan.errors[:default].empty?}"}
    .controls
      %label.checkbox
        =f.check_box :default
        %span 默认语言,只能有一个

  .control-group{:class=>"#{'error' unless @lan.errors[:memo].empty?}"}
    =f.label :memo
    .controls
      =f.text_field :memo
      %span
        - if @lan.errors[:memo].empty?
          该代码的中文说明
        - else
          =@lan.errors[:memo]

  .control-group
    .controls
      = f.submit

app/views/manager/languages/edit.html.haml
%section
  .page-header
    %h2 编辑网站语言种类
  = render 'form'

app/views/manager/languages/index.html.haml
%section
  .page-header
    =link_to '新增语言', new_manager_language_path, :class=>'btn btn-success'
  %table
    %thead
      %tr
        %th 编号
        %th 语言代码
        %th 对应网址
        %th 缺省
        %th 说明
        %th 操作
    %tbody
      - @languages.each do |lan|
        %tr
          %td= lan.id
          %td= lan.code
          %td= lan.link
          %td= "<i class='icon-ok'></i>".html_safe if lan.default
          %td= lan.memo
          %td
            =link_to "<i class='icon-pencil'></i>".html_safe, edit_manager_language_path(lan), :class=>'btn btn-mini btn-info'
            =link_to "<i class='icon-remove'></i>".html_safe, manager_language_path(lan), :confirm=>"是否确认删除语言#{lan.memo}?", :method => :delete, :class=>'btn btn-mini btn-danger'

app/views/manager/languages/new.html.haml
%section
  .page-header
    %h2 新增网站语言种类
  = render 'form'