config/routes.rb
Ftweb::Application.routes.draw do
  root :to => "welcome#index"
  match "locale/:id" => "welcome#set_language", :as => "set_language"

  namespace :manager do
    match "index" => "welcome#index"
    resources :languages
    resources :companies
    resources :categories do 
      member do
        get 'insert'
      end
      collection do
        post 'bat_del'  # 批量删除
      end
    end
    resources :contents do 
      member do
        get 'insert'
      end
      collection do
        post 'bat_del'  # 批量删除
      end
    end
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :fullname, :language_id, :name, :summary, :url
  validates :name, :uniqueness => true
  validates :name, :presence => true

  belongs_to :language
  has_many   :categories
  has_many   :contents
end

app/models/content.rb
class Content < ActiveRecord::Base
  attr_accessible :content, :level, :parent_id, :title, :language_id, :company_id

  belongs_to :company
  belongs_to :language

  before_save :calc_level

protected

  def calc_level
    # 设置初始值
    self.parent_id ||= 0
    self.level = 0

    # 如果有父结点的话，当前级别为父结点级别＋1
    if self.parent_id > 0
      parent = Content.find(self.parent_id)
      self.level = parent.level + 1
    end

    # 当前结点所在的位置
    max_sort = Content.where(:parent_id => self.parent_id).maximum(:sort)
    max_sort ||= 0
    if max_sort == 0
      max_sort = Content.find(self.parent_id).sort
    end

    # 先将之后的结点顺序后移
    sql = "Update contents set sort = sort + 1 where sort > #{max_sort}"
    ActiveRecord::Base.connection.execute(sql)

    # 将数据保存在当前的结点顺序
    self.sort = max_sort + 1
  end

end

app/controllers/manager/categories_controller.rb
# *-*  coding: utf-8  *-*
class Manager::CategoriesController < ApplicationController
  layout "manager"

  def index
    @categories = Category.order("sort")
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def insert
    parent_category = Category.find(params[:id])
    @category = Category.new
    @category.parent_id = params[:id]
    @category.company_id = parent_category.company_id

    render :action => "new"
  end

  def create
    @category = Category.new(params[:category])

    if @category.save
      redirect_to manager_categories_path, :notice => "成功新增内容:#{@category.title}"
    else
      render :action => "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(params[:category])
      redirect_to manager_categories_path, :notice => "内容:#{@category.title}更新完成。"
    else
      render :action => "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to manager_categories_path
  end

  # 批量删除
  def bat_del
    @categories = Category.find(params[:category_ids])
    @categories.each do |category|
      category.destroy
    end

    redirect_to manager_categories_path
  end
end

app/controllers/manager/companies_controller.rb
# *-* coding:utf-8 *-*
class Manager::CompaniesController < ApplicationController
  layout "manager"
  def index
    @companies = Company.all
  end

  def show
    @com = Company.all
  end

  def new
    @com = Company.new
  end

  def create
    @com = Company.new(params[:company])

    if @com.save
      redirect_to manager_companies_path, :notice => "新增公司:#{@com.name}"
    else
      render :action=> "new"
    end
  end

  def edit
    @com = Company.find(params[:id])
  end

  def update
    @com = Company.find(params[:id])

    if @com.update_attributes(params[:company])
      redirect_to manager_companies_path, :notice => "#{@com.name} 相关信息更新完成!"
    else
      render :action => "edit"
    end
  end

  def destroy
    @com = Company.find(params[:id])
    @com.destroy

    redirect_to manager_companies_path
  end
end

app/controllers/manager/contents_controller.rb
# *-* coding:utf-8 *-*
class Manager::ContentsController < ApplicationController
  layout "manager"

  def index
    @contents = Content.order("sort")
  end

  def show
    @content = Content.find(params[:id])
  end

  def new
    @content = Content.new
  end

  def insert
    parent_content = Content.find(params[:id])
    @content = Content.new
    @content.parent_id = params[:id]
    @content.company_id = parent_content.company_id

    render :action => "new"
  end

  def create
    @content = Content.new(params[:content])

    if @content.save
      redirect_to manager_contents_path, :notice => "成功新增内容:#{@content.title}"
    else
      render :action => "new"
    end
  end

  def edit
    @content = Content.find(params[:id])
  end

  def update
    @content = Content.find(params[:id])

    if @content.update_attributes(params[:content])
      redirect_to manager_contents_path, :notice => "内容:#{@content.title}更新完成。"
    else
      render :action => "edit"
    end
  end

  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    redirect_to manager_contents_path
  end

  def bat_del
    @contents = Content.find(params[:content_ids])
    @contents.each do |content|
      content.destroy
    end

    redirect_to manager_contents_path
  end
end

app/controllers/manager/languages_controller.rb
# *-* coding:utf-8 *-*
class Manager::LanguagesController < ApplicationController
  layout "manager"
  def index
    @languages = Language.all
  end

  def show
    @lan = Language.find(params[:id])
  end

  def new
    @lan = Language.new
  end

  def create
    @lan = Language.new(params[:language])

    if @lan.save
      redirect_to manager_languages_path, :notice =>"新语言#{@lan.memo}已经成功增加！"
    else
      render :action=>"new"
    end
  end

  def edit
    @lan = Language.find(params[:id])
  end

  def update
    @lan = Language.find(params[:id])

    if @lan.update_attributes(params[:language])
      redirect_to manager_languages_path, :notice =>"#{@lan.memo}已经更新！"
    else
      render :action=>"edit"
    end
  end

  def destroy
    @lan = Language.find(params[:id])
    @lan.destroy

    redirect_to manager_languages_path
  end
end

app/controllers/manager/welcome_controller.rb
class Manager::WelcomeController < ApplicationController

  layout  "manager"
  def index

  end
end

app/helpers/manager/categories_helper.rb
module Manager::CategoriesHelper
end

app/helpers/manager/companies_helper.rb
module Manager::CompaniesHelper
end

app/helpers/manager/contents_helper.rb
module Manager::ContentsHelper
end

app/helpers/manager/languages_helper.rb
module Manager::LanguagesHelper
end

app/helpers/manager/welcome_helper.rb
module Manager::WelcomeHelper
end

app/views/manager/contents/_form.html.haml
= form_for [:manager, @content] do |f|

  .control-group
    = f.label '标题'
    .controls
      = f.text_field :title

  .control-group
    = f.label '所属语言'
    .controls
      = f.select :language_id, Language.all.collect{|l| [l.memo, l.id]}

  .control-group
    = f.label '所属公司'
    .controls
      = f.select :company_id, Company.all.collect{|l| [l.name, l.id]}

  .control-group
    = f.label '上级栏目'
    .controls
      = f.select :parent_id, Content.all.collect{|l| [l.title, l.id]}, {:include_blank => true}

  .control-group
    = f.label '内容'
    .controls
      = f.text_area :content, :size => '4x10', :class=> 'span10'

  .control-group
    .controls
      = f.submit

= javascript_include_tag "manager/contents"

app/views/manager/contents/edit.html.haml
%section
  .page-header
    %h2 编辑内容
  = render "form"

app/views/manager/contents/index.html.haml
= form_tag bat_del_manager_contents_path do
  %section
    .page-header
      =link_to '新增', new_manager_content_path
      =submit_tag '删除'
    %table
      %thead
        %tr
          %th= check_box_tag "content_all"
          %th ID
          %th sord
          %th 名称
          %th 所属公司
          %th 语言
          %th 操作
      %tbody
        - @contents.each do |con|
          %tr
            %td= check_box_tag "content_ids[]", con.id
            %td= con.id
            %td= con.sort
            %td= ("&nbsp;"*(con.level*8)).html_safe + con.title
            %td= con.company.name
            %td= con.language.memo
            %td
              =link_to "<i class='icon-pencil'></i>".html_safe, edit_manager_content_path(con), :class=> 'btn btn-mini btn-info'
              =link_to "<i class='icon-remove'></i>".html_safe, manager_content_path(con), :confirm=>"是否确认删除#{con.title}?", :method => :delete, :class=> 'btn btn-mini btn-danger'
              =link_to "<i class='icon-plus'></i>".html_safe, insert_manager_content_path(con), :class=> 'btn btn-mini btn-success'


= javascript_include_tag "manager/contents"

app/views/manager/contents/new.html.haml
%section
  .page-header
    %h2 增加内容
  = render "form"