config/routes.rb
Ftweb::Application.routes.draw do
  root :to => "welcome#index"
  match "locale/:id" => "welcome#set_language", :as => "set_language"

  namespace :manager do
    match "index" => "welcome#index"
    resources :languages
    resources :companies
    resources :categories do 
      member do
        get 'insert'
      end
      collection do
        post 'bat_del'  # 批量删除
      end
    end
    resources :contents do 
      member do
        get 'insert'
      end
      collection do
        post 'bat_del'  # 批量删除
      end
    end
  end

end

app/views/layouts/_footer.html.haml
#friend-link
  %ul
    %li= link_to t('Link'), '#'
    %li= link_to '博日', '#'
    %li= link_to '友好', '#'

#footer
  %p
    &copy;2013 Ferrotec China 
    = link_to '浙ICP备05003418号', 'http://www.miibeian.gov.cn/'
    = link_to 'login', manager_index_path

app/views/layouts/_header.html.haml
#header
  #header-logo
    %h1
      = link_to 'Ferrotec', root_path
  #header-info
    #sub-nav
      %ul
        %li= link_to t('Ferrotec(China)'), '#'
        %li= link_to t('Ferrotec(Global)'), '#'
        %li= link_to t('Contact us'), '#'
        %li= link_to t('Sitemap'), '#'
        %li.last= language_link
    #site-search
      = form_tag '/search', :method=>:get
      = text_field_tag 'search'
      = submit_tag t("Search")

app/views/layouts/_manager_header.html.haml
.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container-fluid
      = link_to 'Ferrotec集团网站后台管理', manager_index_path, :class=>'brand'
      .nav-collapse.collapse
        %p.navbar-text.pull-right
          当前登录用户：
          =link_to 'Admin', '#'
        %ul.nav
          %li.active
            = link_to '首页', manager_index_path
          %li
            = link_to 'Link', '#'
          %li
            = link_to 'Link', '#'

app/views/layouts/_manager_sidebar.html.haml
.well.sidebar-nav
  %ul.nav.nav-list
    %li.nav-header 基础设置
    %li{:class=>"#{'active' if self.controller_name=='welcome'}"}=link_to '后台首页', manager_index_path
    %li{:class=>"#{'active' if self.controller_name=='languages'}"}=link_to '语言', manager_languages_path
    %li{:class=>"#{'active' if self.controller_name=='companies'}"}=link_to '公司', manager_companies_path
    %li{:class=>"#{'active' if self.controller_name=='categories'}"}=link_to '目录', manager_categories_path
    %li{:class=>"#{'active' if self.controller_name=='contents'}"}=link_to '内容', manager_contents_path

app/views/layouts/_menu.html.haml
#flash
  %embed{:src=>"/home.swf", :width=>"780", :height=>"250", :type=>"application/x-shockwave-flash"}

#menu
  - display_menu  #显示主菜单

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ferrotec集团网站
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    #container
      = render '/layouts/header'
      = render '/layouts/menu'
      = yield
      = render '/layouts/footer'

app/views/layouts/manager.html.haml
!!!
%html
  %head
    %title Ferrotec集团网站管理
    = stylesheet_link_tag    "manager", :media => "all"
    = javascript_include_tag "manager"
    = csrf_meta_tags
  %body
    = render "layouts/manager_header"
    .container-fluid
      .row-fluid
        .span3
          = render "layouts/manager_sidebar"
        .span9
          - # 加入提示
          - if notice
            .alert.alert-success
              %button.close(data-dismiss="alert"){:type=>"button"} x
              %strong= notice
          = yield